# Generated by Django 2.2.6 on 2019-11-06 17:18

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_permissions(apps, schema_editor):
    group = Group.objects.get(name="Restaurant")

    group.permissions.add(
        Permission.objects.get(codename='add_taxrate'),
        Permission.objects.get(codename='change_taxrate'),
        Permission.objects.get(codename='delete_taxrate'),
        Permission.objects.get(codename='view_taxrate'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=lambda *args, **kwargs: True)
    ]
