# Generated by Django 3.0.1 on 2020-01-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('include_menu', models.BooleanField(default=False, help_text='This category will include menus', verbose_name='Include menus')),
                ('description', models.TextField(blank=True, help_text='This field is not mandatory, but is useful for SEO purposes', verbose_name='description')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('minimum', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='minimum')),
                ('delivery_duration', models.DurationField(verbose_name='delivery duration')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'delivery area',
                'verbose_name_plural': 'delivery areas',
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title visible by the client on the website', max_length=200, verbose_name='title')),
                ('admin_title', models.CharField(blank=True, help_text='This title is only visible by the administrator, so that he can tell apart options that could have the same name on the website. E.g: "Desert for $15 menu" and "Desert for $25 menu"', max_length=200, verbose_name='Administration title')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'menu option',
                'verbose_name_plural': 'menu options',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='tax rate')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_tax_rate', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'Tax rate',
                'verbose_name_plural': 'Tax rates',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(help_text='(Home, Office)', max_length=200, verbose_name='address title')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='company')),
                ('address_first_name', models.CharField(max_length=200, verbose_name='first name')),
                ('address_last_name', models.CharField(max_length=200, verbose_name='last name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=200, verbose_name='address (2)')),
                ('zip_code', models.CharField(max_length=200, verbose_name='zip code')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('phone', models.CharField(max_length=200, verbose_name='phone')),
                ('entrance_code', models.CharField(blank=True, max_length=200, verbose_name='entrance code')),
                ('intercom', models.CharField(blank=True, max_length=200, verbose_name='intercom')),
                ('stairs', models.CharField(blank=True, max_length=200, verbose_name='stairs')),
                ('floor', models.CharField(blank=True, max_length=200, verbose_name='floor')),
                ('apartment_number', models.CharField(blank=True, max_length=200, verbose_name='apartment number')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='comment')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(null=True, upload_to='products', verbose_name='photo')),
                ('thumbnail', models.ImageField(editable=False, null=True, upload_to='thumbs')),
                ('spicy', models.BooleanField(default=False, verbose_name='spicy')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='vegetarian')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price')),
                ('price_with_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price including taxes')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('categories', models.ManyToManyField(to='products.Category', verbose_name='categories')),
                ('tax_rate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_tax_rate', to='products.TaxRate', verbose_name='tax rate')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='MenuOptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='quantity')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mop_option', to='products.MenuOption', verbose_name='option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mop_product', to='products.Product', verbose_name='product')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mop_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'option product',
                'verbose_name_plural': 'option products',
            },
        ),
        migrations.AddField(
            model_name='menuoption',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mo_store', to='products.Store', verbose_name='store'),
        ),
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('zip_code', models.IntegerField(verbose_name='zip code')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('delivery_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_area', to='products.DeliveryArea', verbose_name='delivery area')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dc_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'delivery city',
                'verbose_name_plural': 'delivery cities',
            },
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='da_store', to='products.Store', verbose_name='store'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='products.Store', verbose_name='store'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('options', models.ManyToManyField(to='products.MenuOption', verbose_name='options')),
            ],
            bases=('products.product',),
        ),
    ]
