# Generated by Django 2.1.7 on 2019-08-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='products.Category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
