# Generated by Django 3.0.1 on 2020-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_permissions_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
