# Generated by Django 2.2.6 on 2019-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_author_category_and_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spicy',
            field=models.BooleanField(default=False),
        ),
    ]
