# Generated by Django 3.0.1 on 2020-02-02 07:12

import autoslug.fields
from django.db import migrations

def feed_slug(apps, schema_editor):
    MyModel = apps.get_model('products', 'Product')
    for row in MyModel.objects.all():
        row.slug = row.title
        row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200128_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='-', editable=False, populate_from='title', unique=False),
            preserve_default=False,
        ),
        migrations.RunPython(feed_slug, reverse_code=migrations.RunPython.noop),
    ]
