# Generated by Django 2.2.6 on 2019-10-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20191009_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='products', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spicy',
            field=models.BooleanField(default=False, verbose_name='spicy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(default=False, verbose_name='vegetarian'),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(max_length=200, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
