# Generated by Django 2.2.6 on 2019-10-12 09:44

from django.db import migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Restaurant'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Restaurant',
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191010_2036'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
