# Generated by Django 2.2.6 on 2019-10-12 09:44

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_permissions(apps, schema_editor):
    group = Group.objects.get(name="Restaurant")

    group.permissions.add(
        Permission.objects.get(codename='add_category'),
        Permission.objects.get(codename='change_category'),
        Permission.objects.get(codename='delete_category'),
        Permission.objects.get(codename='view_category'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191012_0944'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=lambda *args, **kwargs: True)
    ]
