# Generated by Django 2.2.6 on 2019-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191019_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbs'),
        ),
    ]
