# Generated by Django 2.2.6 on 2019-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='This field is not mandatory, but is useful for SEO purposes', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='include_menu',
            field=models.BooleanField(default=False, help_text='This category will include menus', verbose_name='Include menus'),
        ),
    ]
