# Generated by Django 2.2.6 on 2019-11-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0023_product_price_with_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_tax_rate', to='store.TaxRate', verbose_name='store'),
        ),
    ]
