# Generated by Django 2.2.6 on 2019-11-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='price including taxes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_tax_rate', to='store.TaxRate', verbose_name='tax rate'),
        ),
    ]
