# Generated by Django 2.2.6 on 2019-11-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20191106_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='products.Store', verbose_name='store'),
        ),
    ]
