# Generated by Django 2.2.7 on 2019-12-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_auto_20191116_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('minimum', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='minimum')),
                ('delivery_duration', models.DurationField(verbose_name='delivery duration')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='da_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'Delivery area',
                'verbose_name_plural': 'Delivery areas',
            },
        ),
    ]
