# Generated by Django 2.2.7 on 2019-12-06 19:11

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_permissions(apps, schema_editor):
    group = Group.objects.get(name="Restaurant")

    group.permissions.add(
        Permission.objects.get(codename='add_deliveryarea'),
        Permission.objects.get(codename='change_deliveryarea'),
        Permission.objects.get(codename='delete_deliveryarea'),
        Permission.objects.get(codename='view_deliveryarea'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_deliveryarea'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=lambda *args, **kwargs: True)
    ]
