# Generated by Django 2.2.7 on 2019-12-06 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0030_auto_20191206_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('zip_code', models.IntegerField(verbose_name='zip code')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('delivery_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_area', to='products.DeliveryArea', verbose_name='delivery area')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dc_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'Delivery city',
                'verbose_name_plural': 'Delivery cities',
            },
        ),
    ]
