# Generated by Django 2.2.7 on 2019-12-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_deliverycity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryarea',
            options={'verbose_name': 'delivery area', 'verbose_name_plural': 'delivery areas'},
        ),
        migrations.AlterModelOptions(
            name='deliverycity',
            options={'verbose_name': 'delivery city', 'verbose_name_plural': 'delivery cities'},
        ),
    ]
