# Generated by Django 2.2.7 on 2019-12-06 19:54

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_permissions(apps, schema_editor):
    group = Group.objects.get(name="Restaurant")

    group.permissions.add(
        Permission.objects.get(codename='add_deliverycity'),
        Permission.objects.get(codename='change_deliverycity'),
        Permission.objects.get(codename='delete_deliverycity'),
        Permission.objects.get(codename='view_deliverycity'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20191206_1948'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=lambda *args, **kwargs: True)
    ]
