# Generated by Django 2.2.7 on 2019-12-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20191206_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
            ],
            bases=('products.product',),
        ),
    ]
