# Generated by Django 2.2.7 on 2019-12-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_auto_20191206_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='quantity')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mop_product', to='products.Product', verbose_name='product')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mop_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'option product',
                'verbose_name_plural': 'option products',
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title visible by the client on the website', max_length=200, verbose_name='title')),
                ('admin_title', models.CharField(blank=True, help_text='This title is only visible by the administraor, so that he can tell apart options that could have the same name on the website. E.g: "Desert for $15 menu" and "Desert for $25 menu"', max_length=200, verbose_name='Administration title')),
                ('author', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mo_store', to='products.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'menu option',
                'verbose_name_plural': 'menu options',
            },
        ),
    ]
