# Generated by Django 2.2.7 on 2019-12-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_menuoption_menuoptionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuoptionproduct',
            name='menu_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mop_option', to='products.MenuOption', verbose_name='option'),
            preserve_default=False,
        ),
    ]
