# Generated by Django 2.2.7 on 2019-12-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_menuoptionproduct_menu_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='options',
            field=models.ManyToManyField(to='products.MenuOption', verbose_name='Options'),
        ),
    ]
