# Generated by Django 2.2.7 on 2019-12-07 12:46

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_permissions(apps, schema_editor):
    group = Group.objects.get(name="Restaurant")

    group.permissions.add(
        Permission.objects.get(codename='add_menuoption'),
        Permission.objects.get(codename='change_menuoption'),
        Permission.objects.get(codename='delete_menuoption'),
        Permission.objects.get(codename='view_menuoption'),
        Permission.objects.get(codename='add_menuoptionproduct'),
        Permission.objects.get(codename='change_menuoptionproduct'),
        Permission.objects.get(codename='delete_menuoptionproduct'),
        Permission.objects.get(codename='view_menuoptionproduct'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_menu_options'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=lambda *args, **kwargs: True)
    ]
