# Generated by Django 2.2.7 on 2019-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20191207_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='admin_title',
            field=models.CharField(blank=True, help_text='This title is only visible by the administrator, so that he can tell apart options that could have the same name on the website. E.g: "Desert for $15 menu" and "Desert for $25 menu"', max_length=200, verbose_name='Administration title'),
        ),
    ]
