# Generated by Django 2.2.7 on 2019-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20191207_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='options',
            field=models.ManyToManyField(to='products.MenuOption', verbose_name='options'),
        ),
    ]
