# Generated by Django 2.2.7 on 2019-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_title',
            field=models.CharField(help_text='(Home, Office)', max_length=200, verbose_name='address title'),
        ),
    ]
