# Generated by Django 2.1.11 on 2019-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='address (2)'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='apartment number'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='entrance_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='entrance code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='floor',
            field=models.CharField(blank=True, max_length=200, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='intercom',
            field=models.CharField(blank=True, max_length=200, verbose_name='intercom'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='stairs',
            field=models.CharField(blank=True, max_length=200, verbose_name='stairs'),
        ),
    ]
