# Generated by Django 2.1.11 on 2019-12-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_store_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='domain',
        ),
    ]
